name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Setup
        run: |
          mkdir -p ~/.ssh
          echo "Setting up SSH directory..."
          ls -la ~/.ssh
      
      - name: Install SSH Key
        run: |
          echo "Installing SSH key..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Key installed. Checking..."
          ls -la ~/.ssh/deploy_key
          
      - name: Add Known Hosts
        run: |
          echo "Adding known hosts..."
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "Known hosts file:"
          cat ~/.ssh/known_hosts
          
      - name: Test SSH Connection (Verbose)
        run: |
          echo "Testing SSH connection with verbose output..."
          ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "Connection test"'
      
      - name: Deploy Files
        if: success()
        run: |
          echo "Deploying files..."
          rsync -avz -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
            --exclude '.git*' \
            --exclude 'node_modules' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/burt-bot/
            
      - name: Run Deployment Commands
        if: success()
        run: |
          echo "Running deployment commands..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /root/burt-bot && \
            echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env && \
            echo "XAI_API_KEY=${{ secrets.XAI_API_KEY }}" >> .env && \
            npm install && \
            pm2 restart burt-bot || pm2 start index.js --name burt-bot && \
            pm2 save
          '